//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace PayProject.Entity
{
    /// <summary>
    /// 实体类Modules。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("modules")]
    [Serializable]
    [DataContract]
    public partial class Modules : Dos.ORM.Entity
    {
        #region Model
        private int _Id;
        private int _ParentId;
        private string _Title;
        private string _Style;
        private string _Controller;
        private string _Action;
        private int _Orderno;
        private bool _Nullity;
        private DateTime _CreateTime;

        /// <summary>
        /// 标识ID
        /// </summary>
        [Field("id")]
        [DataMember]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 父级ID
        /// </summary>
        [Field("ParentId")]
        [DataMember]
        public int ParentId
        {
            get { return _ParentId; }
            set
            {
                this.OnPropertyValueChange("ParentId");
                this._ParentId = value;
            }
        }
        /// <summary>
        /// 菜单名称
        /// </summary>
        [Field("title")]
        [DataMember]
        public string Title
        {
            get { return _Title; }
            set
            {
                this.OnPropertyValueChange("Title");
                this._Title = value;
            }
        }
        /// <summary>
        /// 菜单样式
        /// </summary>
        [Field("style")]
        [DataMember]
        public string Style
        {
            get { return _Style; }
            set
            {
                this.OnPropertyValueChange("Style");
                this._Style = value;
            }
        }
        /// <summary>
        /// 菜单url
        /// </summary>
        [Field("controller")]
        [DataMember]
        public string Controller
        {
            get { return _Controller; }
            set
            {
                this.OnPropertyValueChange("Controller");
                this._Controller = value;
            }
        }
        /// <summary>
        /// 动作
        /// </summary>
        [Field("action")]
        [DataMember]
        public string Action
        {
            get { return _Action; }
            set
            {
                this.OnPropertyValueChange("Action");
                this._Action = value;
            }
        }
        /// <summary>
        /// 排序ID
        /// </summary>
        [Field("orderno")]
        [DataMember]
        public int Orderno
        {
            get { return _Orderno; }
            set
            {
                this.OnPropertyValueChange("Orderno");
                this._Orderno = value;
            }
        }
        /// <summary>
        /// 是否禁用
        /// </summary>
        [Field("nullity")]
        [DataMember]
        public bool Nullity
        {
            get { return _Nullity; }
            set
            {
                this.OnPropertyValueChange("Nullity");
                this._Nullity = value;
            }
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Field("createTime")]
        [DataMember]
        public DateTime CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange("CreateTime");
                this._CreateTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.ParentId,
                _.Title,
                _.Style,
                _.Controller,
                _.Action,
                _.Orderno,
                _.Nullity,
                _.CreateTime,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._ParentId,
                this._Title,
                this._Style,
                this._Controller,
                this._Action,
                this._Orderno,
                this._Nullity,
                this._CreateTime,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "modules");
            /// <summary>
			/// 标识ID
			/// </summary>
			public readonly static Field Id = new Field("id", "modules", "标识ID");
            /// <summary>
			/// 父级ID
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "modules", "父级ID");
            /// <summary>
			/// 菜单名称
			/// </summary>
			public readonly static Field Title = new Field("title", "modules", "菜单名称");
            /// <summary>
			/// 菜单样式
			/// </summary>
			public readonly static Field Style = new Field("style", "modules", "菜单样式");
            /// <summary>
			/// 菜单url
			/// </summary>
			public readonly static Field Controller = new Field("controller", "modules", "菜单url");
            /// <summary>
			/// 动作
			/// </summary>
			public readonly static Field Action = new Field("action", "modules", "动作");
            /// <summary>
			/// 排序ID
			/// </summary>
			public readonly static Field Orderno = new Field("orderno", "modules", "排序ID");
            /// <summary>
			/// 是否禁用
			/// </summary>
			public readonly static Field Nullity = new Field("nullity", "modules", "是否禁用");
            /// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("createTime", "modules", "创建时间");
        }
        #endregion
    }



    //public class Modules
    //{
    //    public int Id { get; set; }
    //    public int ParentId { get; set; }
    //    public string Title { get; set; }
    //    public string Style { get; set; }
    //    public string Controller { get; set; }
    //    public string Action { get; set; }
    //    public int OrderNo { get; set; }
    //    public bool Nullity { get; set; }
    //    public DateTime CreateTime { get; set; }
    //}
}
