//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace PayProject.Entity
{
    /// <summary>
    /// 实体类PayType。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("pay_type")]
    [Serializable]
    [DataContract]
    public partial class PayType : Dos.ORM.Entity
    {
        #region Model
        private int _Type_id;
        private string _Type_name;
        private string _Type_alias;
        private string _Type_note;
        private int _Create_time;
        private int _Update_time;

        /// <summary>
        /// 类型标识
        /// </summary>
        [Field("type_id")]
        [DataMember]
        public int Type_id
        {
            get { return _Type_id; }
            set
            {
                this.OnPropertyValueChange("Type_id");
                this._Type_id = value;
            }
        }
        /// <summary>
        /// 类型名称
        /// </summary>
        [Field("type_name")]
        [DataMember]
        public string Type_name
        {
            get { return _Type_name; }
            set
            {
                this.OnPropertyValueChange("Type_name");
                this._Type_name = value;
            }
        }
        /// <summary>
        /// 类型别名
        /// </summary>
        [Field("type_alias")]
        [DataMember]
        public string Type_alias
        {
            get { return _Type_alias; }
            set
            {
                this.OnPropertyValueChange("Type_alias");
                this._Type_alias = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("type_note")]
        [DataMember]
        public string Type_note
        {
            get { return _Type_note; }
            set
            {
                this.OnPropertyValueChange("Type_note");
                this._Type_note = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("create_time")]
        [DataMember]
        public int Create_time
        {
            get { return _Create_time; }
            set
            {
                this.OnPropertyValueChange("Create_time");
                this._Create_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("update_time")]
        [DataMember]
        public int Update_time
        {
            get { return _Update_time; }
            set
            {
                this.OnPropertyValueChange("Update_time");
                this._Update_time = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Type_id,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Type_id,
                _.Type_name,
                _.Type_alias,
                _.Type_note,
                _.Create_time,
                _.Update_time,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Type_id,
                this._Type_name,
                this._Type_alias,
                this._Type_note,
                this._Create_time,
                this._Update_time,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "pay_type");
            /// <summary>
			/// 类型标识
			/// </summary>
			public readonly static Field Type_id = new Field("type_id", "pay_type", "类型标识");
            /// <summary>
			/// 类型名称
			/// </summary>
			public readonly static Field Type_name = new Field("type_name", "pay_type", "类型名称");
            /// <summary>
			/// 类型别名
			/// </summary>
			public readonly static Field Type_alias = new Field("type_alias", "pay_type", "类型别名");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Type_note = new Field("type_note", "pay_type", "备注");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Create_time = new Field("create_time", "pay_type", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Update_time = new Field("update_time", "pay_type", "");
        }
        #endregion
    }
}