//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace PayProject.Entity
{
    /// <summary>
    /// 实体类SysOrganize。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("sys_organize")]
    [Serializable]
    [DataContract]
    public partial class SysOrganize : Dos.ORM.Entity
    {
        #region Model
        private string _Guid;
        private string _SiteGuid;
        private string _ParentGuid;
        private string _Name;
        private string _ParentName;
        private string _ParentGuidList;
        private int _Layer;
        private int _Sort;
        private bool _Status;
        private DateTime _EditTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("Guid")]
        [DataMember]
        public string Guid
        {
            get { return _Guid; }
            set
            {
                this.OnPropertyValueChange("Guid");
                this._Guid = value;
            }
        }
        /// <summary>
        /// 归属站点
        /// </summary>
        [Field("SiteGuid")]
        [DataMember]
        public string SiteGuid
        {
            get { return _SiteGuid; }
            set
            {
                this.OnPropertyValueChange("SiteGuid");
                this._SiteGuid = value;
            }
        }
        /// <summary>
        /// 父节点
        /// </summary>
        [Field("ParentGuid")]
        [DataMember]
        public string ParentGuid
        {
            get { return _ParentGuid; }
            set
            {
                this.OnPropertyValueChange("ParentGuid");
                this._ParentGuid = value;
            }
        }
        /// <summary>
        /// 组织名称
        /// </summary>
        [Field("Name")]
        [DataMember]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ParentName")]
        [DataMember]
        public string ParentName
        {
            get { return _ParentName; }
            set
            {
                this.OnPropertyValueChange("ParentName");
                this._ParentName = value;
            }
        }
        /// <summary>
        /// 父节点集合
        /// </summary>
        [Field("ParentGuidList")]
        [DataMember]
        public string ParentGuidList
        {
            get { return _ParentGuidList; }
            set
            {
                this.OnPropertyValueChange("ParentGuidList");
                this._ParentGuidList = value;
            }
        }
        /// <summary>
        /// 层级
        /// </summary>
        [Field("Layer")]
        [DataMember]
        public int Layer
        {
            get { return _Layer; }
            set
            {
                this.OnPropertyValueChange("Layer");
                this._Layer = value;
            }
        }
        /// <summary>
        /// 排序
        /// </summary>
        [Field("Sort")]
        [DataMember]
        public int Sort
        {
            get { return _Sort; }
            set
            {
                this.OnPropertyValueChange("Sort");
                this._Sort = value;
            }
        }
        /// <summary>
        /// 状态
        /// </summary>
        [Field("Status")]
        [DataMember]
        public bool Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange("Status");
                this._Status = value;
            }
        }
        /// <summary>
        /// 修改时间
        /// </summary>
        [Field("EditTime")]
        [DataMember]
        public DateTime EditTime
        {
            get { return _EditTime; }
            set
            {
                this.OnPropertyValueChange("EditTime");
                this._EditTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Guid,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Guid,
                _.SiteGuid,
                _.ParentGuid,
                _.Name,
                _.ParentName,
                _.ParentGuidList,
                _.Layer,
                _.Sort,
                _.Status,
                _.EditTime,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Guid,
                this._SiteGuid,
                this._ParentGuid,
                this._Name,
                this._ParentName,
                this._ParentGuidList,
                this._Layer,
                this._Sort,
                this._Status,
                this._EditTime,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "sys_organize");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Guid = new Field("Guid", "sys_organize", "");
            /// <summary>
			/// 归属站点
			/// </summary>
			public readonly static Field SiteGuid = new Field("SiteGuid", "sys_organize", "归属站点");
            /// <summary>
			/// 父节点
			/// </summary>
			public readonly static Field ParentGuid = new Field("ParentGuid", "sys_organize", "父节点");
            /// <summary>
			/// 组织名称
			/// </summary>
			public readonly static Field Name = new Field("Name", "sys_organize", "组织名称");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentName = new Field("ParentName", "sys_organize", "");
            /// <summary>
			/// 父节点集合
			/// </summary>
			public readonly static Field ParentGuidList = new Field("ParentGuidList", "sys_organize", "父节点集合");
            /// <summary>
			/// 层级
			/// </summary>
			public readonly static Field Layer = new Field("Layer", "sys_organize", "层级");
            /// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort", "sys_organize", "排序");
            /// <summary>
			/// 状态
			/// </summary>
			public readonly static Field Status = new Field("Status", "sys_organize", "状态");
            /// <summary>
			/// 修改时间
			/// </summary>
			public readonly static Field EditTime = new Field("EditTime", "sys_organize", "修改时间");
        }
        #endregion
    }

}
