//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace PayProject.Model
{
    /// <summary>
    /// 实体类Pay_order。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("pay_order")]
    [Serializable]
	[DataContract]
    public partial class Pay_order : Entity
    {
        #region Model
		private int _Id;
		private string _Order_id;
		private string _Plat_order_id;
		private int _Pay_type;
		private int _Mch_id;
		private decimal _Order_amount;
		private decimal _Pay_amount;
		private int _Create_time;
		private int _Update_time;
		private int _Finish_time;
		private int _Status;
		private string _Callback_url;
		private string _Notify_url;
		private int? _Notify_status;
		private int? _Notify_times;
		private int? _Notify_lasttime;
		private string _Attach;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		[DataMember]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 订单号
		/// </summary>
		[Field("order_id")]
		[DataMember]
		public string Order_id
		{
			get{ return _Order_id; }
			set
			{
				this.OnPropertyValueChange("Order_id");
				this._Order_id = value;
			}
		}
		/// <summary>
		/// 订单平台流水号
		/// </summary>
		[Field("plat_order_id")]
		[DataMember]
		public string Plat_order_id
		{
			get{ return _Plat_order_id; }
			set
			{
				this.OnPropertyValueChange("Plat_order_id");
				this._Plat_order_id = value;
			}
		}
		/// <summary>
		/// 支付类型
		/// </summary>
		[Field("pay_type")]
		[DataMember]
		public int Pay_type
		{
			get{ return _Pay_type; }
			set
			{
				this.OnPropertyValueChange("Pay_type");
				this._Pay_type = value;
			}
		}
		/// <summary>
		/// 商户号
		/// </summary>
		[Field("mch_id")]
		[DataMember]
		public int Mch_id
		{
			get{ return _Mch_id; }
			set
			{
				this.OnPropertyValueChange("Mch_id");
				this._Mch_id = value;
			}
		}
		/// <summary>
		/// 订单金额
		/// </summary>
		[Field("order_amount")]
		[DataMember]
		public decimal Order_amount
		{
			get{ return _Order_amount; }
			set
			{
				this.OnPropertyValueChange("Order_amount");
				this._Order_amount = value;
			}
		}
		/// <summary>
		/// 实际支付金额
		/// </summary>
		[Field("pay_amount")]
		[DataMember]
		public decimal Pay_amount
		{
			get{ return _Pay_amount; }
			set
			{
				this.OnPropertyValueChange("Pay_amount");
				this._Pay_amount = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("create_time")]
		[DataMember]
		public int Create_time
		{
			get{ return _Create_time; }
			set
			{
				this.OnPropertyValueChange("Create_time");
				this._Create_time = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("update_time")]
		[DataMember]
		public int Update_time
		{
			get{ return _Update_time; }
			set
			{
				this.OnPropertyValueChange("Update_time");
				this._Update_time = value;
			}
		}
		/// <summary>
		/// 订单完成时间
		/// </summary>
		[Field("finish_time")]
		[DataMember]
		public int Finish_time
		{
			get{ return _Finish_time; }
			set
			{
				this.OnPropertyValueChange("Finish_time");
				this._Finish_time = value;
			}
		}
		/// <summary>
		/// 订单状态   0  未支付   1   支付成功
		/// </summary>
		[Field("status")]
		[DataMember]
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 订单同步回调Url
		/// </summary>
		[Field("callback_url")]
		[DataMember]
		public string Callback_url
		{
			get{ return _Callback_url; }
			set
			{
				this.OnPropertyValueChange("Callback_url");
				this._Callback_url = value;
			}
		}
		/// <summary>
		/// 订单异步通知Url
		/// </summary>
		[Field("notify_url")]
		[DataMember]
		public string Notify_url
		{
			get{ return _Notify_url; }
			set
			{
				this.OnPropertyValueChange("Notify_url");
				this._Notify_url = value;
			}
		}
		/// <summary>
		/// 异步通知状态
		/// </summary>
		[Field("notify_status")]
		[DataMember]
		public int? Notify_status
		{
			get{ return _Notify_status; }
			set
			{
				this.OnPropertyValueChange("Notify_status");
				this._Notify_status = value;
			}
		}
		/// <summary>
		/// 通知次数
		/// </summary>
		[Field("notify_times")]
		[DataMember]
		public int? Notify_times
		{
			get{ return _Notify_times; }
			set
			{
				this.OnPropertyValueChange("Notify_times");
				this._Notify_times = value;
			}
		}
		/// <summary>
		/// 最后通知时间
		/// </summary>
		[Field("notify_lasttime")]
		[DataMember]
		public int? Notify_lasttime
		{
			get{ return _Notify_lasttime; }
			set
			{
				this.OnPropertyValueChange("Notify_lasttime");
				this._Notify_lasttime = value;
			}
		}
		/// <summary>
		/// 附加参数
		/// </summary>
		[Field("attach")]
		[DataMember]
		public string Attach
		{
			get{ return _Attach; }
			set
			{
				this.OnPropertyValueChange("Attach");
				this._Attach = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Order_id,
				_.Plat_order_id,
				_.Pay_type,
				_.Mch_id,
				_.Order_amount,
				_.Pay_amount,
				_.Create_time,
				_.Update_time,
				_.Finish_time,
				_.Status,
				_.Callback_url,
				_.Notify_url,
				_.Notify_status,
				_.Notify_times,
				_.Notify_lasttime,
				_.Attach,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Order_id,
				this._Plat_order_id,
				this._Pay_type,
				this._Mch_id,
				this._Order_amount,
				this._Pay_amount,
				this._Create_time,
				this._Update_time,
				this._Finish_time,
				this._Status,
				this._Callback_url,
				this._Notify_url,
				this._Notify_status,
				this._Notify_times,
				this._Notify_lasttime,
				this._Attach,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pay_order");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id", "pay_order", "");
            /// <summary>
			/// 订单号
			/// </summary>
			public readonly static Field Order_id = new Field("order_id", "pay_order", "订单号");
            /// <summary>
			/// 订单平台流水号
			/// </summary>
			public readonly static Field Plat_order_id = new Field("plat_order_id", "pay_order", "订单平台流水号");
            /// <summary>
			/// 支付类型
			/// </summary>
			public readonly static Field Pay_type = new Field("pay_type", "pay_order", "支付类型");
            /// <summary>
			/// 商户号
			/// </summary>
			public readonly static Field Mch_id = new Field("mch_id", "pay_order", "商户号");
            /// <summary>
			/// 订单金额
			/// </summary>
			public readonly static Field Order_amount = new Field("order_amount", "pay_order", "订单金额");
            /// <summary>
			/// 实际支付金额
			/// </summary>
			public readonly static Field Pay_amount = new Field("pay_amount", "pay_order", "实际支付金额");
            /// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field Create_time = new Field("create_time", "pay_order", "创建时间");
            /// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field Update_time = new Field("update_time", "pay_order", "更新时间");
            /// <summary>
			/// 订单完成时间
			/// </summary>
			public readonly static Field Finish_time = new Field("finish_time", "pay_order", "订单完成时间");
            /// <summary>
			/// 订单状态   0  未支付   1   支付成功
			/// </summary>
			public readonly static Field Status = new Field("status", "pay_order", "订单状态   0  未支付   1   支付成功");
            /// <summary>
			/// 订单同步回调Url
			/// </summary>
			public readonly static Field Callback_url = new Field("callback_url", "pay_order", "订单同步回调Url");
            /// <summary>
			/// 订单异步通知Url
			/// </summary>
			public readonly static Field Notify_url = new Field("notify_url", "pay_order", "订单异步通知Url");
            /// <summary>
			/// 异步通知状态
			/// </summary>
			public readonly static Field Notify_status = new Field("notify_status", "pay_order", "异步通知状态");
            /// <summary>
			/// 通知次数
			/// </summary>
			public readonly static Field Notify_times = new Field("notify_times", "pay_order", "通知次数");
            /// <summary>
			/// 最后通知时间
			/// </summary>
			public readonly static Field Notify_lasttime = new Field("notify_lasttime", "pay_order", "最后通知时间");
            /// <summary>
			/// 附加参数
			/// </summary>
			public readonly static Field Attach = new Field("attach", "pay_order", "附加参数");
        }
        #endregion
	}
}