//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace PayProject.Model
{
    /// <summary>
    /// 实体类Pay_plat。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("pay_plat")]
    [Serializable]
	[DataContract]
    public partial class Pay_plat : Entity
    {
        #region Model
		private int _Plat_id;
		private string _Plat_name;
		private string _Plat_class;
		private string _Req_gateway;
		private string _Pay_gateway;
		private string _Pay_type_list;

		/// <summary>
		/// 平台标识
		/// </summary>
		[Field("plat_id")]
		[DataMember]
		public int Plat_id
		{
			get{ return _Plat_id; }
			set
			{
				this.OnPropertyValueChange("Plat_id");
				this._Plat_id = value;
			}
		}
		/// <summary>
		/// 平台名称
		/// </summary>
		[Field("plat_name")]
		[DataMember]
		public string Plat_name
		{
			get{ return _Plat_name; }
			set
			{
				this.OnPropertyValueChange("Plat_name");
				this._Plat_name = value;
			}
		}
		/// <summary>
		/// 平台类名
		/// </summary>
		[Field("plat_class")]
		[DataMember]
		public string Plat_class
		{
			get{ return _Plat_class; }
			set
			{
				this.OnPropertyValueChange("Plat_class");
				this._Plat_class = value;
			}
		}
		/// <summary>
		/// 查询网关地址
		/// </summary>
		[Field("req_gateway")]
		[DataMember]
		public string Req_gateway
		{
			get{ return _Req_gateway; }
			set
			{
				this.OnPropertyValueChange("Req_gateway");
				this._Req_gateway = value;
			}
		}
		/// <summary>
		/// 支付网关地址
		/// </summary>
		[Field("pay_gateway")]
		[DataMember]
		public string Pay_gateway
		{
			get{ return _Pay_gateway; }
			set
			{
				this.OnPropertyValueChange("Pay_gateway");
				this._Pay_gateway = value;
			}
		}
		/// <summary>
		/// 支持支付方式，多个使用逗号分隔
		/// </summary>
		[Field("pay_type_list")]
		[DataMember]
		public string Pay_type_list
		{
			get{ return _Pay_type_list; }
			set
			{
				this.OnPropertyValueChange("Pay_type_list");
				this._Pay_type_list = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Plat_id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Plat_id,
				_.Plat_name,
				_.Plat_class,
				_.Req_gateway,
				_.Pay_gateway,
				_.Pay_type_list,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Plat_id,
				this._Plat_name,
				this._Plat_class,
				this._Req_gateway,
				this._Pay_gateway,
				this._Pay_type_list,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pay_plat");
            /// <summary>
			/// 平台标识
			/// </summary>
			public readonly static Field Plat_id = new Field("plat_id", "pay_plat", "平台标识");
            /// <summary>
			/// 平台名称
			/// </summary>
			public readonly static Field Plat_name = new Field("plat_name", "pay_plat", "平台名称");
            /// <summary>
			/// 平台类名
			/// </summary>
			public readonly static Field Plat_class = new Field("plat_class", "pay_plat", "平台类名");
            /// <summary>
			/// 查询网关地址
			/// </summary>
			public readonly static Field Req_gateway = new Field("req_gateway", "pay_plat", "查询网关地址");
            /// <summary>
			/// 支付网关地址
			/// </summary>
			public readonly static Field Pay_gateway = new Field("pay_gateway", "pay_plat", "支付网关地址");
            /// <summary>
			/// 支持支付方式，多个使用逗号分隔
			/// </summary>
			public readonly static Field Pay_type_list = new Field("pay_type_list", "pay_plat", "支持支付方式，多个使用逗号分隔");
        }
        #endregion
	}
}