//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace PayProject.Model
{
    /// <summary>
    /// 实体类Settle_mch。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("settle_mch")]
    [Serializable]
	[DataContract]
    public partial class Settle_mch : Entity
    {
        #region Model
		private int _Id;
		private string _Mch_id;
		private string _Mch_name;
		private string _Mch_key;
		private string _Mch_key2;
		private bool _Nullity;
		private int _Plat_id;
		private int _Rate;
		private string _Callback_host;
		private int _Create_time;
		private int _Update_time;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		[DataMember]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 商户号
		/// </summary>
		[Field("mch_id")]
		[DataMember]
		public string Mch_id
		{
			get{ return _Mch_id; }
			set
			{
				this.OnPropertyValueChange("Mch_id");
				this._Mch_id = value;
			}
		}
		/// <summary>
		/// 商户名称 自定义 管理名称
		/// </summary>
		[Field("mch_name")]
		[DataMember]
		public string Mch_name
		{
			get{ return _Mch_name; }
			set
			{
				this.OnPropertyValueChange("Mch_name");
				this._Mch_name = value;
			}
		}
		/// <summary>
		/// 商户密钥
		/// </summary>
		[Field("mch_key")]
		[DataMember]
		public string Mch_key
		{
			get{ return _Mch_key; }
			set
			{
				this.OnPropertyValueChange("Mch_key");
				this._Mch_key = value;
			}
		}
		/// <summary>
		/// 商户密钥2
		/// </summary>
		[Field("mch_key2")]
		[DataMember]
		public string Mch_key2
		{
			get{ return _Mch_key2; }
			set
			{
				this.OnPropertyValueChange("Mch_key2");
				this._Mch_key2 = value;
			}
		}
		/// <summary>
		/// 是否开启
		/// </summary>
		[Field("nullity")]
		[DataMember]
		public bool Nullity
		{
			get{ return _Nullity; }
			set
			{
				this.OnPropertyValueChange("Nullity");
				this._Nullity = value;
			}
		}
		/// <summary>
		/// 平台标识
		/// </summary>
		[Field("plat_id")]
		[DataMember]
		public int Plat_id
		{
			get{ return _Plat_id; }
			set
			{
				this.OnPropertyValueChange("Plat_id");
				this._Plat_id = value;
			}
		}
		/// <summary>
		/// 费率千分比
		/// </summary>
		[Field("rate")]
		[DataMember]
		public int Rate
		{
			get{ return _Rate; }
			set
			{
				this.OnPropertyValueChange("Rate");
				this._Rate = value;
			}
		}
		/// <summary>
		/// 回调主机名
		/// </summary>
		[Field("callback_host")]
		[DataMember]
		public string Callback_host
		{
			get{ return _Callback_host; }
			set
			{
				this.OnPropertyValueChange("Callback_host");
				this._Callback_host = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_time")]
		[DataMember]
		public int Create_time
		{
			get{ return _Create_time; }
			set
			{
				this.OnPropertyValueChange("Create_time");
				this._Create_time = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_time")]
		[DataMember]
		public int Update_time
		{
			get{ return _Update_time; }
			set
			{
				this.OnPropertyValueChange("Update_time");
				this._Update_time = value;
			}
		}

        public string BankList { get; set; }
        public int? Max_money { get; set; }
        public int? Min_money { get; set; }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Mch_id,
				_.Mch_name,
				_.Mch_key,
				_.Mch_key2,
				_.Nullity,
				_.Plat_id,
				_.Rate,
				_.Callback_host,
				_.Create_time,
				_.Update_time,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Mch_id,
				this._Mch_name,
				this._Mch_key,
				this._Mch_key2,
				this._Nullity,
				this._Plat_id,
				this._Rate,
				this._Callback_host,
				this._Create_time,
				this._Update_time,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "settle_mch");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id", "settle_mch", "");
            /// <summary>
			/// 商户号
			/// </summary>
			public readonly static Field Mch_id = new Field("mch_id", "settle_mch", "商户号");
            /// <summary>
			/// 商户名称 自定义 管理名称
			/// </summary>
			public readonly static Field Mch_name = new Field("mch_name", "settle_mch", "商户名称 自定义 管理名称");
            /// <summary>
			/// 商户密钥
			/// </summary>
			public readonly static Field Mch_key = new Field("mch_key", "settle_mch", "商户密钥");
            /// <summary>
			/// 商户密钥2
			/// </summary>
			public readonly static Field Mch_key2 = new Field("mch_key2", "settle_mch", "商户密钥2");
            /// <summary>
			/// 是否开启
			/// </summary>
			public readonly static Field Nullity = new Field("nullity", "settle_mch", "是否开启");
            /// <summary>
			/// 平台标识
			/// </summary>
			public readonly static Field Plat_id = new Field("plat_id", "settle_mch", "平台标识");
            /// <summary>
			/// 费率千分比
			/// </summary>
			public readonly static Field Rate = new Field("rate", "settle_mch", "费率千分比");
            /// <summary>
			/// 回调主机名
			/// </summary>
			public readonly static Field Callback_host = new Field("callback_host", "settle_mch", "回调主机名");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Create_time = new Field("create_time", "settle_mch", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Update_time = new Field("update_time", "settle_mch", "");
        }
        #endregion
	}
}